version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./API
      dockerfile: Dockerfile.dev
    volumes:
      - ./API:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/cesizen-dev
      - JWT_SECRET=dev-secret
    depends_on:
      - mongo

  backoffice:
    build:
      context: ./BACKOFFICE
      dockerfile: Dockerfile.dev
    volumes:
      - ./BACKOFFICE:/app
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - api

  app:
    build:
      context: ./APP
      dockerfile: Dockerfile.dev
    volumes:
      - ./APP:/app
    ports:
      - "8081:8081"
    environment:
      - EXPO_PUBLIC_API_URL=http://localhost:3000/api
    depends_on:
      - api

volumes:
  mongo-data:
