version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cesizen_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./API
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/cesizen_test?schema=public
    depends_on:
      db:
        condition: service_healthy
