
FROM node:18 AS builder

WORKDIR /app
COPY . .

RUN npm install expo-cli -g

RUN npm install --legacy-peer-deps

RUN npx expo export --platform web --output-dir dist

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
