FROM node:18

WORKDIR /app
COPY . .

RUN npm install --legacy-peer-deps

RUN npx expo export --platform web --output-dir dist

FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
