FROM node:20 AS builder

WORKDIR /app

ARG VITE_API_URL

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80