FROM node:18

WORKDIR /app
COPY . .

RUN npm install --legacy-peer-deps
RUN npm run build

# Tu peux aussi lancer les tests ici si tu veux que le container "fail" s'ils échouent
# RUN npm run test

CMD ["node", "dist/main.js"]
