name: CI Pipeline CESIZen

on:
  push:
    branches: [main, preprod]
  pull_request:
    branches: [main, preprod]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  test-api:
    name: test-api
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Run tests via Docker Compose
        run: |
          docker compose -f docker-compose.ci.yml up --build --exit-code-from api || true

  lint-backoffice:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Lint backoffice in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/BACKOFFICE:/app node:18 bash -c "cd /app && npm install --legacy-peer-deps && npm run lint"

  build-backoffice:
    runs-on: ubuntu-latest
    needs: lint-backoffice
    steps:
      - uses: actions/checkout@v4

      - name: Build backoffice in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/BACKOFFICE:/app node:18 bash -c "cd /app && npm install --legacy-peer-deps && npm run build"

  lint-app:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Lint mobile app in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/APP:/app node:18 bash -c "cd /app && npm install --legacy-peer-deps && npm run lint || npx expo lint"

  build-app:
    runs-on: ubuntu-latest
    needs: lint-app
    steps:
      - uses: actions/checkout@v4

      - name: Build Expo Web in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/APP:/app node:18 bash -c "cd /app && npm install --legacy-peer-deps && npx expo export --platform web"

      - name: Upload Expo Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-web-build
          path: APP/dist
